### ISSUE TITLE
valur parametres fit dans 2_Methode.ipynb

### ISSUE THREAD

**Issue by laurentperrinet** [chloepasturel/AnticipatorySPEM#11]
les valeurs montrées sont les valeurs par défaut

![image](https://user-images.githubusercontent.com/381808/38247561-0f9dcd50-3746-11e8-9917-c48d55e1a6ee.png)

**Comment by laurentperrinet** [comment]
peut-être lié au patch dans https://github.com/chloepasturel/AnticipatorySPEM/commit/24014000402c11137f5e1764a0629a74621a17a1#diff-da99a584fe39552fcc22c544c0a87775

**Comment by laurentperrinet** [comment]
C’est donc a cause de lmfit = a corriger plus tard mais pour l’instant c’est bon

**Comment by chloepasturel** [comment]
ça doit venir de la dernière version de lmfit, étant trop récente je ne trouve pour l'instant pas de solution, je pense que le plus simple est de revenir a la version 0.9.7 qui marche correctement

**Comment by laurentperrinet** [comment]
ok - on verra ça apres l'atelier...

**Comment by laurentperrinet** [comment]
essayer de faire marcher avec la derniere version

**Comment by chloepasturel** [comment]
résolu
