### ISSUE TITLE
figures with overlays

### ISSUE THREAD

**Issue by laurentperrinet** [chloepasturel/AnticipatorySPEM#15]
pour un talk il est pratique qu'on fasse des figures avec différentes couches

**Comment by laurentperrinet** [comment]
il me semble qu'on l'ait ffait - je trouve pas trace du code particulier : on pouiyrrait le lier ici puis fermer l'issue...

**Comment by chloepasturel** [comment]
c'est pas dans 3_Results_1 et 3_Results_2 ?

**Comment by laurentperrinet** [comment]
si, il me semble, donc on peut fermer...
