### ISSUE TITLE
inter-individual differences

### ISSUE THREAD

**Issue by laurentperrinet** [chloepasturel/AnticipatorySPEM#16]
notebook 4_meta

**Comment by laurentperrinet** [comment]
linked to https://github.com/laurentperrinet/bayesianchangepoint/issues/4

**Comment by laurentperrinet** [comment]
par rapport à 2018-04-09_param_TAU.ipynb ,

- vérifier que c'est fait sur le dernier code BCP
-   tester différents scores pour trouver le h optimal, cf https://github.com/laurentperrinet/bayesianchangepoint/blob/master/notebooks/test_hazardrate.ipynb :

```
          #score[i_mode, i_scan, i_block] = np.mean(np.log2(1.e-12+bcp.likelihood(o[(border+1):], p_hat[border:-1], r_hat[border:-1])))
            #score[i_mode, i_scan, i_block] = np.sum(np.abs(p_hat - p[:, i_block, 0]))
            score[i_mode, i_scan, i_block] = np.log2(np.mean(bcp.likelihood(o[(border+1):], p_hat[border:-1], r_hat[border:-1])))
```

**Comment by chloepasturel** [comment]
voir :
- 4_Meta_analysis.ipynb
- dev/2018-07-27_4_Meta_analysis.ipynb
- dev/2018-07-27_4_Meta_analysis_New.ipynb
